services:
  nuxbill:
    container_name: netpass
    pull_policy: always
    build: ./
    restart: unless-stopped
    environment:
      TZ: Africa/Nairobi
    depends_on:
      - mysql

  mysql:
    container_name: mysql
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: "netpass"
      MYSQL_DATABASE: "netpass"
      MYSQL_USER: "netpass"
      MYSQL_PASSWORD: "netpass"
