services:
  netbill:
    container_name: netbill
    pull_policy: always
    build:
      context: .
      dockerfile: Dockerfile
    restart: unless-stopped
    environment:
      - TZ= Africa/Nairobi
      - MYSQL_ROOT_PASSWORD=$MYSQL_ROOT_PASSWORD
      - MYSQL_DATABASE=$MYSQL_DATABASE
      - MYSQL_USER=$MYSQL_USER
      - MYSQL_PASSWORD=$MYSQL_PASSWORD
    volumes:
      - 
        type: bind
        source: ./netbill/config/config.php
        target: /var/www/html/config.php
        content: ""

